# Lab 1 - Dimensionality Reduction
## Machine Learning II

Moisés Alfonso Guerrero Jiménez

In [9]:
# Modules
import numpy as np

### Workshop I
1. Simulate a random rectangular matrix A
    - What is the rank and trace of A?
    - What is the determinant of A?
    - Can you invert A? How?
    - How are eigenvalues and eigenvectors of A'A and AA' related? What interesting differences can you notice between both?
    - See [https://sites.cs.ucsb.edu/~mturk/Papers/jcn.pdf](https://sites.cs.ucsb.edu/~mturk/Papers/jcn.pdf)

**R/** For simulating a rectangular matrix $A$ with dimensions $m\times n$ we could specify inputs for dimensions $m$ and $n$. For this exercise, I will simulate matrix $A$ only with integer values by using `numpy.random.randint()`, that lets us to set lower and higher integers to include in the matrix and its size $m\times n$.

In [21]:
# 1. Random matrix simulation
low = int(input("Lowest integer of the matrix: "))
high = int(input("Highest integer of the matrix: "))
m = int(input("Number of rows: "))
n = int(input("Number of columns: "))
np.random.seed(seed=1234) # Optional: Configuring seed for pseudo-random generation
A = np.random.randint(low=low, high=high, size=(m, n))
print(f"Generating matrix A_{m}x{n} with integer values between {low} and {high}...")
print(f"A = \n{A}")

Generating matrix A_7x5 with integer values between -10 and 15...
A = 
[[  5   9  -4  11   2]
 [ 10  14   5   7  13]
 [ -1   1   2  12  14]
 [  6  -5   6  -1  12]
 [  5   8   6   2  -5]
 [ -8  -4  -7  -3   1]
 [-10  -1   1   6  -7]]


Rank is defined as the number of linearly independent columns of a matrix $A \in \mathbb{R}^{m\times n}$.

In [22]:
# Rank and trace of A
np.linalg.matrix_rank(A)

5